services:
  wizrd-db:
    container_name: wizrd-db
    image: pgrouting/pgrouting:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wizrd
    # Uncomment the following lines if you're running WizRD outside Docker
    # ports:
    #   - "5432:5432"
    volumes:
      - wizrd-vol:/var/lib/postgresql/data
    networks:
      - wizrd-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "psql -U admin -d wizrd -c 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3

  wizrd-preprocessing:
    container_name: wizrd-preprocessing
    build:
      context: ./wizrd-preprocessing
      dockerfile: Dockerfile
    depends_on:
      wizrd-db:
        condition: service_healthy
    restart: "no"
    networks:
      - wizrd-net

  wizrd-pgadmin:
    container_name: wizrd-pgadmin
    image: elestio/pgadmin:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: sal@unimib.it
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - wizrd-db
    networks:
      - wizrd-net
    restart: unless-stopped

  wizrd:
    container_name: wizrd
    build: .
    ports:
      - "8000:8000"
    depends_on:
      wizrd-db:
        condition: service_healthy
      wizrd-preprocessing:
        condition: service_completed_successfully
    networks:
      - wizrd-net
    restart: always
    command: ["/bin/sh", "-c", "sleep 30 && ./wizrd-backend"]

networks:
  wizrd-net:
    driver: bridge
    external: true

volumes:
  wizrd-vol:
